remote_theme: vcavallo/jekyll-hackcss
theme_mode: markdown

# pretty necessary for the footer (unless removed)
your_name: David Tench
# email: dtench@pm.me

# this is how the menu panel is constructed:
navigation:
  - text: Home
    url: /
  - text: Examples
    url: /examples
  - text: Bio
    url: /bio
  - text: Publications
    url: /publications


# if you want to use something like the card-based 'projects' in examples.html
projects:
  - name: jekyll-hackcss
    description: A jekyll gem-style theme based on hack.css
    link: https://github.com/vcavallo/jekyll-hackcss
  - name: Impostor Roster
    description: A place for newbies of all experience level to admit their shortcomings
    link: http://impostorroster.com
  - name: Rate my Refactor
    description: Advice and discussion about code design and refactoring, crowd-sourced from a community of experts in your field
    link: http://www.ratemyrefactor.com/
  - name: Termodoro
    description: A simple CLI pomodoro client ruby gem
    link: https://github.com/vcavallo/termodoro

# if you plan to use the social links in the footer
social:
  - service: github
    username: tenchd
    link: https://github.com/tenchd
  - service: twitter
    username: davidtench_
    link: https://x.com/davidtench_
