remote_theme: vcavallo/jekyll-hackcss
theme_mode: markdown

# pretty necessary for the footer (unless removed)
your_name: David Tench
# email: dtench@pm.me

# this is how the menu panel is constructed:
navigation:
  - text: Home
    url: /
  - text: Bio
    url: /bio
  - text: Publications
    url: /publications
  - text: Software
    url: /software
  - text: Recent News
    url: /news


# if you want to use something like the card-based 'projects' in examples.html
projects:
  - name: GraphZeppelin
    description: storage-friendly connected components sketching
    link: https://github.com/GraphStreamingProject/GraphZeppelin
  - name: Landscape
    description: distributed connectivity sketching
    link: https://github.com/GraphStreamingProject/Landscape
  - name: Mesh
    description: impossible compacting memory management for C++
    link: https://github.com/plasma-umass/Mesh
  - name: spec_spars
    description: a prototype streaming spectral sparsifier
    link: https://github.com/tenchd/spec_spars

# if you plan to use the social links in the footer
social:
  - service: github
    username: tenchd
    link: https://github.com/tenchd
  - service: twitter
    username: davidtench_
    link: https://x.com/davidtench_
